"use client";
import React, { useState } from "react";
import Accordion from "./Accordion";

function FAQ() {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);

  const toggleAccordion = (index: number) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  const accordionData = [
    {
      title: "What does SRS stand for in software development?",
      content:
        "SRS in software development stands for Software Requirements Specification - a document that describes the features, functions, and constraints of a software system or application in detail. The SRS serves as a guide for developers and engineers to understand what is required to build the system, and it also helps stakeholders understand what to expect from the final product. It typically includes requirements for system features, interfaces, performance, quality, and security, among other aspects. ",
    },
    {
      title: "What is the SRS Generator tool provided by Blueprint.AI?",
      content:
        "The SRS AI Generator is a free tool offered by Blueprint.AI, designed to help users draft a Software Requirements Specification (SRS) for their software projects using AI technology. This tool aims to streamline the initial planning phase by generating a preliminary SRS based on user input.",
    },
    {
      title: "How can the SRS Generator benefit my project planning process?",
      content:
        "The SRS AI Generator simplifies the creation of an SRS document, saving time and resources. It provides a clear and comprehensive plan that minimizes misunderstandings among project stakeholders, ensuring everyone is aligned with the project's scope and objectives.",
    },
    {
      title:
        "What kind of projects can benefit from using Blueprint.AI's SRS Generator?",
      content:
        "Projects ranging from cutting-edge mobile apps and sophisticated web platforms to powerful business tools can benefit from using the SRS AI Generator. It's designed to cater to a wide range of software development projects.",
    },
    {
      title: "How accurately does the AI generate the draft SRS?",
      content:
        "The draft SRS generated by the AI provides a solid starting point based on the information provided by the user. However, reviewing and customizing the draft in collaboration with your team is recommended to ensure it fully captures your project's requirements.",
    },
    {
      title:
        "How does the AI SRS Generator compares to traditional methods of creating an SRS?",
      content:
        "The SRS AI Generator accelerates the SRS creation process by using AI to generate a preliminary document based on user input, saving time and resources compared to traditional methods that often involve more manual effort and deliberation.",
    },
  ];

  return (
    <div className="flex  justify-center items-center ">
      <div
        id="FAQ"
        className="my-20 mx-5 md:w-[80%] bg-[#00000046] rounded-3xl space-y-8 flex flex-col md:flex-row justify-center items-center py-10 px-10"
      >
        <p
          style={{ fontFamily: " 'Cinzel Variable', serif" }}
          className="text-4xl text-center tracking-wider font-medium text-white md:px-10 font-gradient"
        >
          Frequently Asked Questions
        </p>
        <div className="accordion flex flex-col justify-center items-center">
            <div className="md:px-10">
                {accordionData.map((item, index) => (
                    <Accordion
                        key={index}
                        title={item.title}
                        content={item.content}
                        isActive={activeIndex === index}
                        onToggle={() => toggleAccordion(index)}
                    />
                ))}
            </div>
        </div>
      </div>
    </div>
  );
}

export default FAQ;
